<<<<<<< HEAD
# Generated by Django 4.2.2 on 2023-07-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=32, unique=True, verbose_name='사용자 아이디')),
                ('naver_searchID', models.CharField(max_length=128, unique=True, verbose_name='네이버 검색 client ID')),
                ('naver_searchAPI', models.CharField(max_length=128, unique=True, verbose_name='네이버 검색 API 토큰')),
                ('naver_keywordID', models.CharField(max_length=128, unique=True, verbose_name='네이버 검색 client ID')),
                ('naver_keywordAPI', models.CharField(max_length=128, unique=True, verbose_name='네이버 검색 API 토큰')),
                ('google_visionID', models.CharField(max_length=128, unique=True, verbose_name='구글 비전 clinet ID')),
                ('google_visionAPI', models.CharField(max_length=128, unique=True, verbose_name='구글 비전 API 토큰')),
            ],
            options={
                'db_table': 'token',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='사용자 아이디'),
        ),
    ]
=======
# Generated by Django 4.2.2 on 2023-07-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=32, unique=True, verbose_name='사용자 아이디')),
                ('naver_searchID', models.CharField(max_length=128, unique=True, verbose_name='네이버 검색 client ID')),
                ('naver_searchAPI', models.CharField(max_length=128, unique=True, verbose_name='네이버 검색 API 토큰')),
                ('naver_keywordID', models.CharField(max_length=128, unique=True, verbose_name='네이버 검색 client ID')),
                ('naver_keywordAPI', models.CharField(max_length=128, unique=True, verbose_name='네이버 검색 API 토큰')),
                ('google_visionID', models.CharField(max_length=128, unique=True, verbose_name='구글 비전 clinet ID')),
                ('google_visionAPI', models.CharField(max_length=128, unique=True, verbose_name='구글 비전 API 토큰')),
            ],
            options={
                'db_table': 'token',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='사용자 아이디'),
        ),
    ]
>>>>>>> 719cd225de0c04018c059ed171d0c81cd36fa789
