# Generated by Django 4.2.2 on 2023-07-13 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_token_info_remove_user_id_alter_user_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='token_info',
            name='id',
        ),
        migrations.AlterField(
            model_name='token_info',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='token_info', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
