<<<<<<< HEAD
# Generated by Django 4.2.2 on 2023-07-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_token_info_naver_keywordapi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token_info',
            name='google_visionID',
            field=models.CharField(default='', max_length=3000, unique=True, verbose_name='구글 비전 clinet ID'),
        ),
    ]
=======
# Generated by Django 4.2.2 on 2023-07-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_token_info_naver_keywordapi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token_info',
            name='google_visionID',
            field=models.CharField(default='', max_length=3000, unique=True, verbose_name='구글 비전 clinet ID'),
        ),
    ]
>>>>>>> 719cd225de0c04018c059ed171d0c81cd36fa789
