# Generated by Django 4.2.2 on 2023-08-17 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('account', '0007_alter_token_info_google_searchapi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QnA',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='qna_info', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('title', models.CharField(default='', max_length=100, verbose_name='제목')),
                ('contents', models.CharField(default='', max_length=1000, verbose_name='문의 내용')),
                ('date', models.CharField(default='', max_length=1000, verbose_name='문의 작성시간')),
            ],
            options={
                'db_table': 'qna',
            },
        ),
    ]
