# Generated by Django 4.2.2 on 2023-08-17 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_qna_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='id',
            field=models.BigAutoField(auto_created=True, default=123, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qna',
            name='user_id',
            field=models.CharField(default='', max_length=100, verbose_name='아이디'),
        ),
    ]
