# Generated by Django 4.2.2 on 2023-08-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_qna_id_alter_qna_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='qna',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='이름'),
        ),
        migrations.AddField(
            model_name='qna',
            name='phone_number',
            field=models.CharField(default='', max_length=100, verbose_name='전화번호'),
        ),
    ]
