# Generated by Django 4.2.2 on 2023-07-18 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_user_remove_token_info_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token_info',
            name='naver_keywordAPI',
        ),
        migrations.RemoveField(
            model_name='token_info',
            name='naver_keywordID',
        ),
        migrations.AddField(
            model_name='token_info',
            name='google_searchAPI',
            field=models.CharField(default='', max_length=128, unique=True, verbose_name='구글 검색 API 토큰'),
        ),
        migrations.AddField(
            model_name='token_info',
            name='google_searchID',
            field=models.CharField(default='', max_length=128, unique=True, verbose_name='구글 검색 client ID'),
        ),
        migrations.AlterField(
            model_name='token_info',
            name='google_visionAPI',
            field=models.CharField(default='', max_length=128, unique=True, verbose_name='구글 비전 API 토큰 암호정보'),
        ),
        migrations.AlterField(
            model_name='token_info',
            name='google_visionID',
            field=models.CharField(default='', max_length=128, unique=True, verbose_name='구글 비전 clinet ID'),
        ),
        migrations.AlterField(
            model_name='token_info',
            name='naver_searchAPI',
            field=models.CharField(default='', max_length=128, unique=True, verbose_name='네이버 검색 API 토큰'),
        ),
        migrations.AlterField(
            model_name='token_info',
            name='naver_searchID',
            field=models.CharField(default='', max_length=128, unique=True, verbose_name='네이버 검색 client ID'),
        ),
    ]
